import type { AppLang } from '../services/locale.service';

const DEFAULT_PROFILE = 'hotel';

/** Keys match establishment preset ids (`onboarding.profile_id`). */
const SUGGESTED_BY_PROFILE: Record<string, Record<AppLang, readonly string[]>> = {
  hotel: {
    en: [
      'Standard',
      'Superior',
      'Deluxe',
      'Premium',
      'Junior Suite',
      'Suite',
      'Executive',
      'Family Room',
      'Connecting Room',
      'Accessible',
    ],
    ar: [
      'قياسية',
      'سوبيريور',
      'ديلوكس',
      'بريميوم',
      'جناح صغير',
      'جناح',
      'تنفيذية',
      'عائلية',
      'غرف متصلة',
      'لذوي الإعاقة',
    ],
  },
  serviced_apartments: {
    en: [
      'Studio',
      'One bedroom',
      'Two bedroom',
      'Three bedroom',
      'Loft',
      'Duplex',
      'Penthouse',
      'Executive apartment',
      'Serviced suite',
    ],
    ar: [
      'استوديو',
      'غرفة وصالة',
      'غرفتين وصالة',
      'ثلاث غرف وصالة',
      'لوفت',
      'دوبلكس',
      'بنتهاوس',
      'شقة تنفيذية',
      'جناح فندقي',
    ],
  },
  residential_compound: {
    en: [
      'Villa',
      'Twin villa',
      'Townhouse',
      'Duplex',
      'Apartment',
      'Penthouse',
      'Chalet',
      'Studio unit',
      'Garden home',
    ],
    ar: [
      'فيلا',
      'فيلا توأم',
      'تاون هاوس',
      'دوبلكس',
      'شقة',
      'بنتهاوس',
      'شاليه',
      'استوديو',
      'دور بحديقة',
    ],
  },
  corporate_housing: {
    en: [
      'Single',
      'Twin',
      'Double',
      'Studio',
      'One bedroom',
      'Two bedroom',
      'Family unit',
      'Executive unit',
      'Accessible unit',
    ],
    ar: [
      'فردي',
      'توأم',
      'مزدوج',
      'استوديو',
      'غرفة وصالة',
      'غرفتين وصالة',
      'وحدة عائلية',
      'وحدة تنفيذية',
      'وحدة لذوي الإعاقة',
    ],
  },
  hospital: {
    en: [
      'Standard ward',
      'Semi-private',
      'Private room',
      'VIP room',
      'ICU bed',
      'Isolation room',
      'Maternity',
      'Pediatric',
      'Recovery room',
    ],
    ar: [
      'جناح عام',
      'نصف خاص',
      'غرفة خاصة',
      'غرفة VIP',
      'سرير عناية مركزة',
      'غرفة عزل',
      'ولادة',
      'أطفال',
      'غرفة نقاهة',
    ],
  },
  student_housing: {
    en: [
      'Single room',
      'Double room',
      'Triple room',
      'Shared room',
      'Studio',
      'En-suite single',
      'En-suite double',
      'Accessible room',
      'Apartment style',
    ],
    ar: [
      'غرفة فردية',
      'غرفة مزدوجة',
      'غرفة ثلاثية',
      'غرفة مشتركة',
      'استوديو',
      'فردية بحمام',
      'مزدوجة بحمام',
      'غرفة لذوي الإعاقة',
      'شقة طلابية',
    ],
  },
  university: {
    en: [
      'Single room',
      'Double room',
      'Triple room',
      'Shared room',
      'Studio',
      'En-suite single',
      'En-suite double',
      'Accessible room',
      'Graduate studio',
    ],
    ar: [
      'غرفة فردية',
      'غرفة مزدوجة',
      'غرفة ثلاثية',
      'غرفة مشتركة',
      'استوديو',
      'فردية بحمام',
      'مزدوجة بحمام',
      'غرفة لذوي الإعاقة',
      'استوديو دراسات عليا',
    ],
  },
};

export function suggestedRoomTypesForProfile(profileId: string | null | undefined, lang: AppLang): string[] {
  const profile = profileId && SUGGESTED_BY_PROFILE[profileId] ? profileId : DEFAULT_PROFILE;
  const block = SUGGESTED_BY_PROFILE[profile] ?? SUGGESTED_BY_PROFILE[DEFAULT_PROFILE];
  return [...block[lang]];
}
